
title: ParameterX的博客

email: 1942013510@qq.com

description: >- # this means to ignore newlines until "baseurl:"
  ParameterX's Blog.

baseurl: "/" # the subpath of your site, e.g. /blog

url: "parameterx.github.io" # the base hostname & protocol for your site, e.g. http://example.com